//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int userid { get; set; }
        public int eventtypeid { get; set; }
        public int transid { get; set; }
        public string source { get; set; }
        public string logmessage { get; set; }
        public System.DateTime logtimestamp { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual User User { get; set; }
        public virtual EmailLog EmailLog { get; set; }
    }
}
