//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int transid { get; set; }
        public string emailaddress { get; set; }
        public int emailstatus { get; set; }
        public System.DateTime senttimestamp { get; set; }
    
        public virtual AuditLog AuditLog { get; set; }
    }
}
